version: '3.1'
services:
  react-admin:
    image: react-admin
    ports: 
      - "3000:3000"
    networks:
      - mongo-compose-network
  apirest:
    image: apirest
    ports:
      - "5000:5000"
    networks:
      - mongo-compose-network
    depends_on:
      - mongo
      - mongo-express
    restart: unless-stopped
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: <user>
      MONGO_INITDB_ROOT_PASSWORD: <password>
    volumes: 
      - mongodata:/data/db
    networks: 
      - mongo-compose-network
  mongo-express:
    image: mongo-express
    restart: on-failure
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: <user>
      ME_CONFIG_MONGODB_ADMINPASSWORD: <password>
      ME_CONFIG_MONGODB_URL: mongodb://<user>:<password>@mongo:27017/<db>
    volumes: 
      - mongodata:/data/db
    networks: 
      - mongo-compose-network
    depends_on:
      - mongo
networks:
  mongo-compose-network:
    driver: bridge
volumes:
  mongodata: